### ISSUE TITLE
geteditorstate is not defined

### ISSUE THREAD

**Issue by gmchaturvedi1** [brijeshb42/draft-text-editor-tutorial#1]
i am just copying the same example but getEditorState is not a function error is coming when i fire any command.
 
i am fairly new todraftjs.

Kindly suggest me.

regards
gmchaturvedi

**Comment by brijeshb42** [comment]
Can you please elaborate. Which file, which line?

**Comment by brijeshb42** [comment]
I encountered this issue today. You are probably using the latest `draft-js-plugins-editor` version `2.0.0-beta11` in which, the method signature has changed.

You should change the `handleKeyCommand` line in the `src/plugins/basicTextStylePlugin.js` to

```js
handleKeyCommand(command, editorState, { getEditorState, setEditorState})
```

Or you can downgrade to version 2.0.0-beta10.

Read [here](http://bitwiser.in/2017/05/11/creating-rte-part-3-entities-and-decorators.html#note).
